# Generated by Django 4.0.4 on 2022-05-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIData',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='apiparameters',
            name='description_parameter',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='apiweb',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
