# Generated by Django 4.0.4 on 2022-05-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backed_api', '0002_delete_apidata_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIparameters',
            new_name='Parameters',
        ),
    ]
