# Generated by Django 4.0.4 on 2022-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed_api', '0003_rename_apiparameters_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='title_parameter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
