# Generated by Django 4.0.4 on 2022-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed_api', '0004_parameters_title_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiweb',
            name='X_RapidAPI_Host',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='apiweb',
            name='X_RapidAPI_Key',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
